// Command seed populates the flash sale database with demo products and users.
//
// It is idempotent: products are matched on their unique name and users on
// their email, so running it repeatedly resets stock rather than creating
// duplicates. It prints the product IDs it wrote, which are the IDs a client
// needs in order to place an order.
package main

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/flashsale/common/env"
	"github.com/joho/godotenv"
	_ "github.com/lib/pq" // database/sql driver
	"golang.org/x/crypto/bcrypt"
)

// defaultSeedPassword is used for the demo accounts when SEED_PASSWORD is not
// set. These accounts exist for local development only.
const defaultSeedPassword = "password123"

type product struct {
	Name  string
	Price int
	Stock int
}

type user struct {
	Email string
	Role  string
}

func main() {
	if err := run(); err != nil {
		log.Fatalf("seed: %v", err)
	}
}

func run() error {
	// A missing .env is fine; the variables may already be in the environment.
	_ = godotenv.Load("../.env")
	_ = godotenv.Load()

	// Same resolution as the services: assembled from POSTGRES_* parts unless
	// POSTGRES_URL overrides them.
	dbURL, err := env.PostgresDSN()
	if err != nil {
		return err
	}

	password := os.Getenv("SEED_PASSWORD")
	if password == "" {
		password = defaultSeedPassword
		log.Printf("SEED_PASSWORD not set, using the built-in development password")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	db, err := sql.Open("postgres", dbURL)
	if err != nil {
		return fmt.Errorf("open database: %w", err)
	}
	defer func() { _ = db.Close() }()

	if err := db.PingContext(ctx); err != nil {
		return fmt.Errorf("connect to database: %w", err)
	}
	fmt.Println("Connected to database, seeding...")

	if err := seedProducts(ctx, db); err != nil {
		return err
	}
	if err := seedUsers(ctx, db, password); err != nil {
		return err
	}

	fmt.Println("\nDatabase seeded successfully.")
	return nil
}

func seedProducts(ctx context.Context, db *sql.DB) error {
	products := []product{
		{"iPhone 15 Pro", 999, 100},
		{"MacBook Air M3", 1299, 8},
		{"AirPods Pro", 249, 200},
		{"iPad Pro", 799, 75},
		{"Apple Watch", 399, 150},
	}

	// Matching on the unique name makes re-seeding reset stock instead of
	// inserting a second copy of every product.
	const query = `
		INSERT INTO products (name, price, stock)
		VALUES ($1, $2, $3)
		ON CONFLICT (name) DO UPDATE SET price = EXCLUDED.price, stock = EXCLUDED.stock
		RETURNING id`

	fmt.Println("\nProducts:")
	for _, p := range products {
		var id string
		if err := db.QueryRowContext(ctx, query, p.Name, p.Price, p.Stock).Scan(&id); err != nil {
			return fmt.Errorf("seed product %q: %w", p.Name, err)
		}
		// Print the ID: it is what a client needs to place an order, and it is
		// generated by the database rather than fixed in this file.
		fmt.Printf("  %s  %-16s stock=%d\n", id, p.Name, p.Stock)
	}
	return nil
}

func seedUsers(ctx context.Context, db *sql.DB, password string) error {
	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return fmt.Errorf("hash seed password: %w", err)
	}

	users := []user{
		{"user@example.com", "user"},
		{"admin@example.com", "admin"},
		{"tester@example.com", "tester"},
	}

	const query = `
		INSERT INTO users (email, password_hash, role)
		VALUES ($1, $2, $3)
		ON CONFLICT (email) DO UPDATE SET password_hash = EXCLUDED.password_hash
		RETURNING id`

	fmt.Println("\nUsers:")
	for _, u := range users {
		var id string
		if err := db.QueryRowContext(ctx, query, u.Email, string(hash), u.Role).Scan(&id); err != nil {
			return fmt.Errorf("seed user %q: %w", u.Email, err)
		}
		fmt.Printf("  %s  %-20s role=%s\n", id, u.Email, u.Role)
	}
	return nil
}
