FROM golang:1.23-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY order-worker/go.mod order-worker/go.sum ./
RUN go mod download

COPY order-worker/ .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o order-worker .

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/order-worker .

CMD ["./order-worker"]
