# Order Service Build
FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY order-service/go.mod order-service/go.sum ./
RUN go mod download

COPY order-service/ .
RUN CGO_ENABLED=0 GOOS=linux go build -o /order-service main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /order-service .

EXPOSE 8084
CMD ["./order-service"]
