FROM golang:1.23-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY purchase-service/go.mod purchase-service/go.sum ./
RUN go mod download

COPY purchase-service/ .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o purchase-service .

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/purchase-service .

EXPOSE 8081

CMD ["./purchase-service"]
